### ISSUE TITLE
Angle of custom sun position with decimal value

### ISSUE THREAD

**Issue by Bolukan** [jensrossbach/node-red-contrib-chronos#107]
The input of the angle of custom sun positions is rounded to a whole degree. For sun angles the decimal is relevant. P.e. sun angles are like sunrise start (-0.833) en and sunrise end (-0.3). I propose decimal values are accepted.

Possible location for the code change is [data.angle = angle.spinner("value");](https://github.com/jensrossbach/node-red-contrib-chronos/blob/c63ae38b96dd6f6bc10eb61a0897cbe8bf2fb536/nodes/config.html#L274), as the spinner supports only whole numbers - which is ok.

**Comment by jensrossbach** [comment]
It looks like the value is stored in the precision as you enter it and the rounding takes place only when you reopen the UI of the configuration node (whenever the value is passed to the spinner again). However I agree that this is not so nice and should be changed. How many decimal places do you require for the angle?

**Comment by Bolukan** [comment]
To add common implemented sun positions (amateur, civil, blueHour, goldenHourDawnStart, etc) no decimal is needed. 
The start of sunrise is defined as -0.833 degree. So 3 decimals should be enough in all situations.

I really like the clean structure to add extra positions centrally available for use in all nodes. My use case is to use a sun position in multiple nodes that is defined centrally.

**Comment by jensrossbach** [comment]
Issue has been fixed with release [1.18.4](https://github.com/jensrossbach/node-red-contrib-chronos/releases/tag/v1.18.4).
