### ISSUE TITLE
time filter with multiple outputs

### ISSUE THREAD

**Issue by golfvert** [jensrossbach/node-red-contrib-chronos#110]
Hello,
Thanks for the great set of nodes!!
Like the `switch` node where we have multiple output, I would suggest in the time filter node to have one output per condition.
Typically, I have various time range say 0 -> 6, 6 -> 12 and 12 -> 0. I would like to have one output per range. At the moment, I'd need three time range node, one with each `between`.
At the moment we have logical or and logical and, it would be another option (not sure about the name...) .
Thanks!

**Comment by jensrossbach** [comment]
Hi @golfvert, why don't you use a time switch node for your use case? I don't see the benefit of adding multiple outputs to the time filter node as this would actually make this node the same as the time switch node.

**Comment by golfvert** [comment]
My apologies. I didn't realise it was doable like that!!

**Comment by golfvert** [comment]
Wrong request ;)
Thanks for the quick answer!!
