### ISSUE TITLE
Elevation in config

### ISSUE THREAD

**Issue by Destix** [jensrossbach/node-red-contrib-chronos#115]
It's will be nice if there was an option to add elevation in config, because it affects sunrise and sunset times.

**Comment by jensrossbach** [comment]
Can you explain a bit more what you mean with "elevation"? Because the term "elevation" is often used for the solar zenith angle of the sun but I assume that you mean the altitude above sea level of your own position, correct?

**Comment by jensrossbach** [comment]
No feedback from issue submitter since long time, closing...
