### ISSUE TITLE
Scheduler node: time portion of status text showing as German

### ISSUE THREAD

**Issue by zachowj** [jensrossbach/node-red-contrib-chronos#179]
**Describe the bug**

When using the "time of day" event for the scheduler node. The status text of the node shows German for the time section and English for the "next event" section when the browser default locale is set to English.

It does show English correctly when the "sun/moon position" is selected.

**To reproduce**
screenshots show setup

**Expected behavior**
To show English for both when the browser locale is set to English.

**Screenshots**

![image](https://github.com/jensrossbach/node-red-contrib-chronos/assets/37859597/fd12816b-c63b-4d63-bc14-f502f15a7d55)

![image](https://github.com/jensrossbach/node-red-contrib-chronos/assets/37859597/f77967de-1ab5-4961-b291-8adfe207e464)

![image](https://github.com/jensrossbach/node-red-contrib-chronos/assets/37859597/a7f16507-716a-431a-8d02-dd67a5d59e8e)

**Context information**
Please complete the following information.
 - Platform & OS:
 - node-red-contrib-chronos version: 1.25.0
 - Node-RED version: 3.1.11 and 4.0
 - Node.js version: 20

**Additional information**

**Comment by jensrossbach** [comment]
There's not much I can do about this. The status text contains a static part (e.g., "next event") which is translated using the Node-RED translation functionality and a dynamic part (the time part) which is translated by the moment library. The latter always uses the configured language of the backend (i.e., either the configured language of the Node-RED runtime from `settings.js` or - if nothing is configured there - the configured language of the operating system). The translation of the static part via Node-RED seems to use the configured language of the editor (i.e., the setting that you configure in the browser). However, this doesn't seem to be consistent, I've also seen different behavior of Node-RED here.

**Hint:** Ensure that the language configured in the Node-RED editor and in the Node-RED runtime match, then these effects shouldn't occur.

Here are some related topics:
https://discourse.nodered.org/t/node-status-translation/49907
https://discourse.nodered.org/t/feature-request-node-status-translation-context/80368

**Comment by jensrossbach** [comment]
Sorry, I missed the part with the inconsistency between time of day and sun or moon time. So I made more tests and were able to reproduce the issue. I found a small bug that I will correct in a new patch release.

**Comment by jensrossbach** [comment]
Should be solved with release [1.25.1](https://github.com/jensrossbach/node-red-contrib-chronos/releases/tag/v1.25.1).
