### ISSUE TITLE
Ausgabe-Port für Ereigniszeiten

### ISSUE THREAD

**Issue by kritzeleien** [jensrossbach/node-red-contrib-chronos#184]
node red:  Current version: 18.0.2
chronus version: 1.25.2

 scheduler node,  - Ausgabe-Port für Ereigniszeiten - funktioniert nicht

**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Context information**
Please complete the following information.
 - Platform & OS:
 - node-red-contrib-chronos version:
 - Node-RED version:
 - Node.js version:

**Additional information**
Add any other information about the problem here.

**Comment by kritzeleien** [comment]
Hallo. Ich versuche den Fehler mal zu beschreiben.Ich habe ein - events: state node -  mit ein input_boolean.stundlich.nachrichten AN/AUS an dem dann eine  - chance node - mit der Regel/ setze msg.payload to value JSONata payload = 'on' ? true : false  hängt. Dann kommt ein scheduler node mit einem Zeitplan - 00:00:00 uhr   msg.payload = true, 01:00:00 uhr msg.payload = true  usw. bis 23:00:00 - bei den Optionen im scheduler ist angescheckt:  mit inaktiven Zeitplan starten sonst alles abgescheckt.Das funktioniert auch!Wenn jetzt aber im scheduler unter Optionen - Mit inaktiven Zeitplan starten: angescheckt undAusgabe-Port für Ereigniszeiten: angescheckt istKommt kein 'on' oder 'off' mehr von - events: state node.--Gesendet mit der WEB.DE Mail AppAm 07.07.24, 12:15 schrieb Jens-Uwe Rossbach ***@***.***>:

   
  Ich kann keinen Fehler reproduzieren, bei mir funktioniert es ohne Probleme. Ein paar mehr Details zum Fehler wären hilfereich (dafür ist ja auch das Template gedacht) und ggf. Screenshots und Traces auf mindestens Debug-Level.

**Comment by jensrossbach** [comment]
Das hört sich so an als wäre alles richtig. Die Option "Mit inaktivem Zeitplan starten" bedeutet, dass der Scheduler in deaktiviertem Zustand startet, d.h. es werden keine Ereignisse getriggert bis diese explizit über eine Eingangsnachricht aktiviert werden. Wenn diese Option also aktiviert ist, sendet der Scheduler keine Nachrichten mehr.

**Comment by kritzeleien** [comment]
Ja, das ist genau richtig. 
![Screenshot 2024-07-08 070648](https://github.com/jensrossbach/node-red-contrib-chronos/assets/101063497/c36fcb55-0504-433f-a41d-77221c238e78)
![Screenshot 2024-07-08 071051](https://github.com/jensrossbach/node-red-contrib-chronos/assets/101063497/f80c40db-21e9-4be8-9654-afd0d6347eca)

**Comment by jensrossbach** [comment]
Sollte mit Version [1.25.3](https://github.com/jensrossbach/node-red-contrib-chronos/releases/tag/v1.25.3) gelöst sein.

**Comment by kritzeleien** [comment]
Super ,jetzt geht es wieder. Vielen Dank für die Bemühungen und Nodes👍--Gesendet mit der WEB.DE Mail AppAm 08.07.24, 20:07 schrieb Jens-Uwe Rossbach ***@***.***>:

   
  Sollte mit Version 1.25.3 gelöst sein.
