### ISSUE TITLE
Time Switch node reset itself with "Sun Position" based conditions

### ISSUE THREAD

**Issue by ub1m4j0r** [jensrossbach/node-red-contrib-chronos#34]
Hi jensrossbach.
I have an issue with the "Time Switch" node.
I setup a node with the following three conditions (between 06:45 and 07:20, between Sunset (start) and 23:30 and otherwise):

array[3]
0: object
operator: "between"
label: "between 06:45 and 07:20"
operands: array[2]
0: object
type: "time"
value: "06:45"
offset: 0
random: false
1: object
type: "time"
value: "07:20"
offset: 0
random: false
1: object
operator: "between"
label: "between Sunset (start) and 23:30"
operands: array[2]
0: object
type: "sun"
value: "sunsetStart"
offset: 0
random: false
1: object
type: "time"
value: "23:30"
offset: 0
random: false
2: object
operator: "otherwise"
label: "otherwise"

Everything is fine and the node works fine, but if I change the first condition (between 06:45 and 07:20) with something like "between 06:45 and Sunrise (start)" on save, the node reset itself, all conditions disappear and the "Time Switch" node appears unconfigured on the workspace
I'm using Nodered 1.2.7 with node-red-contrib-chronos 1.9.0.
Could be a bug?
Thank you :-)

**Comment by jensrossbach** [comment]
Fixed with release 1.9.1.
