### ISSUE TITLE
how to full msg

### ISSUE THREAD

**Issue by kuradi** [jensrossbach/node-red-contrib-chronos#60]
my goal is to pass flow.boo to payload, but i have no success.
i have been tried
```
{
    "topic": "topic/POWER1",
    "payload": "{flow.boo}"
}
```
and 
`{
    "topic": "topic/POWER1",
    "payload": "{{flow.boo}}"
}`
please advise

**Comment by jensrossbach** [comment]
@kuradi Please have a look at release 1.16.0 which I published today. Now you can specify the output using a JSONata expression which in fact allows you to include content from context variables.

For instance, taking your example from the beginning of this discussion, you can write something like this:
```
{
    "topic": "topic/POWER1",
    "payload": $flowContext("boo")
}
```
