### ISSUE TITLE
node status on scheduler block

### ISSUE THREAD

**Issue by vtacquet** [jensrossbach/node-red-contrib-chronos#66]
**Is your feature request related to a problem? Please describe.**
It would be nice to see when the next scheduled event would occur on the "scheduler" block in the editor (_like "next message at xx:xx" on the repeat block_)

**Describe the solution you'd like**
A simple node status on the scheduler block with the date of the next event (ex. for sunrise: next message at 07:06), taking into account that there are multiple events and when it has passed the next one should be shown

**Additional context**
ex for the following schedule
![CleanShot 2021-12-10 at 10 47 58](https://user-images.githubusercontent.com/5128967/145553637-b509dd10-4a78-4439-b408-30d34b21f670.png)
![CleanShot 2021-12-10 at 10 48 39](https://user-images.githubusercontent.com/5128967/145553798-5dd9c697-499a-453d-829e-005d4921487f.png)

**Comment by jensrossbach** [comment]
Hi, realizing this is a bit more complex than for the repeat node because of multiple possible events but definitely not impossible. I have to investigate this in more detail.

**Comment by vtacquet** [comment]
Yeah, pretty sure it’s not that easy, but would make debugging more practical. Very nice node by the way, there are many others (even containing what is in this enhancement but they all lack the simplicity of having multiple payloads on different moments, this is the best one !)

**Comment by jensrossbach** [comment]
Thank you, I'm glad that you like the node.

**Comment by jensrossbach** [comment]
Feature has been published with version 1.16.0.

@vtacquet Sorry that it took so long time, actually I had this feature finished already some weeks ago. But I had a couple of additional features I wanted to release with 1.16 as well and my time was very limited in the last month.

**Comment by vtacquet** [comment]
thx @jensrossbach it looks perfect !
