### ISSUE TITLE
Offset value is only applied if it is divisible by 5

### ISSUE THREAD

**Issue by vtacquet** [jensrossbach/node-red-contrib-chronos#78]
**Describe the bug**
the offset value is only applied if it is divisible by 5 (= if it exists in the dropdown list), every other value (eg. 12 or 17) is rounded to the nearest value in the list

**To reproduce**
1. Create an even and set the offset to 12
2. Click on Done
3. Re-open the node
4. The offset is changed to 10

**Expected behavior**
The offset should stay what was entered 

**Screenshots**
https://user-images.githubusercontent.com/5128967/150681142-72e0cdbe-ba94-418f-ae81-078daf2a569b.mp4

**Context information**
Please complete the following information.
 - Platform & OS: docker
 - node-red-contrib-chronos version: 1.16.0
 - Node-RED version: 2.0.6
 - Node.js version: 14.17.6

**Comment by jensrossbach** [comment]
Fixed in release v1.17.0.
